apiVersion: v1
kind: Pod
metadata:
  name: lesson1-pod
  labels:
    env: dev
    app: test
    tier: frontend
    owner: Artem
spec:
  containers:
    - name: container-nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: container-api
      image: tomcat:8.5.38
      ports:
        - containerPort: 8080

 