apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-service-deployment-2
  labels:
    app: app-service-2
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: test
  template:
    metadata:
      labels:
        project: test # Selecting Pods with those Labels
    spec: 
      containers:
        - name: test-app
          image: nginx:latest
          ports:
            - containerPort: 80
        - name: test-db
          image: tomcat:8.5.38
          ports: 
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: two-pod-service
  labels:
    env: dev
    owner: Artem
spec:
  type: ClusterIP
  selector:
    project: test      # Selecting Pods with those Labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 8002       # Port Service
      targetPort: 80   # Port Pod
    - name: db-listener
      protocol: TCP
      port: 8001       # Port Service
      targetPort: 8080 # Port Pod

