apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ .Release.Name }}-app
    name: {{ .Release.Name }}-app-service
spec:
    type: NodePort
    selector:
        app: {{ .Release.Name }}-app
    ports:
        - name: {{ .Release.Name }}-app-listener
          protocol: TCP
          port: 80
          targetPort: 80
