apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-db
    labels:
        app: {{ .Release.Name }}-db
spec:
    replicas: {{ .Values.dbReplicaCount }}
    selector:
        matchLabels:
            project: {{ .Release.Name }}-db
    template:
        metadata:
            labels:
                project: {{ .Release.Name }}-db
        spec:
            containers:
                - name: {{ .Release.Name }}-db
                  image: {{ .Values.dbImage }}
                  ports:
                    - containerPort: 3306
                  env: 
                    - name: MYSQL_ROOT_PASSWORD
                      value: "1111"
                    - name: MYSQL_DATABASE
                      value: code_masters