apiVersion: v1
kind: Service
metadata:
    labels: 
        app: {{ .Release.Name }}-db
    name: {{ .Release.Name }}-db-svc
spec:
    type: NodePort
    selector:
        app: {{ .Release.Name }}-db
    ports:
        - name: {{ .Release.Name }}-db-listener
          protocol: TCP
          port: 3306
          targetPort: 3306
